export const APP_SIDEBAR_UPDATED = 'APP_SIDEBAR_UPDATED';

export const FILTER_SIZE_REQUESTED = 'FILTER_SIZE_REQUESTED';
export const FILTER_SIZE_RESOLVED = 'FILTER_SIZE_RESOLVED';
export const FILTER_SIZE_REJECTED = 'FILTER_SIZE_REJECTED';

export const FILTER_COLOR_REQUESTED = 'FILTER_COLOR_REQUESTED';
export const FILTER_COLOR_RESOLVED = 'FILTER_COLOR_RESOLVED';
export const FILTER_COLOR_REJECTED = 'FILTER_COLOR_REJECTED';

export const FILTER_SEARCH_REQUESTED = 'FILTER_SEARCH_REQUESTED';
export const FILTER_SEARCH_RESOLVED = 'FILTER_SEARCH_RESOLVED';
export const FILTER_SEARCH_REJECTED = 'FILTER_SEARCH_REJECTED';
